src/utils/mutations.ts
=> fix(types): optional network asset id

package-lock.json, package.json
https://stickyjs.netlify.app/sticky
Updating pkgs to match what we do internally https://stickyjs.netlify.app/sticky
Fixes #
=> chore(packages): to use sticky

README.md, examples/contented.config.mjs, examples/levain-graphql-examples/README.md, examples/package.json, examples/turbo.json, pnpm-lock.yaml, pnpm-workspace.yaml, turbo.json
As per title.
Prior-art: https://github.com/vercel/examples
=> feat(examples): configure contented

examples/levain-graphql-examples/README.md
=> docs(examples): fix readme links

README.md
=> chore(workflows): add README.md for project

packages/levain-json/LevainJson.ts, packages/levain-json/package.json, pnpm-lock.yaml
=> chore(levain-json): setup levain-json for schema.json

examples/contented.config.mjs, examples/neobank/README.md, package.json, packages/create-levain-app/README.md, packages/create-levain-app/cli.js, packages/create-levain-app/package.json, packages/create-levain-app/src/ProjectProgram.ts, packages/create-levain-app/src/TemplateProgram.ts, packages/create-levain-app/src/cli.ts, packages/create-levain-app/src/utils/FolderEmpty.ts, packages/create-levain-app/src/utils/NpmNameValid.ts, packages/create-levain-app/tsconfig.build.json, packages/create-levain-app/tsconfig.json, packages/levain-json/package.json, packages/levain-json/tsconfig.json, pnpm-lock.yaml
=> feat(create-levain-app): create-levain-app

.github/workflows/ci.yml, .github/workflows/release.yml, examples/levain-graphql-examples/package.json, package.json
=> chore(workflows): fix publishing

.github/workflows/release.yml
=> chore(workflows): npm config set to global

.github/workflows/release.yml, examples/package.json, packages/create-levain-app/package.json, packages/levain-json/package.json
As per title, when private === false.
=> chore(workflows): conditional release.yml

.github/workflows/release.yml, packages/create-levain-app/src/ProjectProgram.ts, packages/create-levain-app/src/TemplateProgram.ts
=> chore(workflows): use deterministic version

examples/neobank/package.json, package.json, packages/create-levain-app/src/ProjectProgram.ts, pnpm-lock.yaml
=> chore(workflows): fix building due to missing package.json in rootDir

packages/create-levain-app/src/TemplateProgram.ts
Due to the nuances of using npm as a `generator`:
- `LICENSE` have to be removed because it is automatically added.
- `.npmignore` need to be replaced to `.gitignore`.
=> chore(workflows): add override files to replace certain files in template

README.md, examples/neobank/README.md, packages/create-levain-app/README.md
Frontmatter for `create-levain-app` and `levain-examples`.
=> chore(workflows): add frontmatter for levain

examples/package.json, package.json, pnpm-lock.yaml
=> chore(*): bump typescript, pnpm, & contented

examples/neobank/app/layout.tsx, examples/neobank/app/page.tsx, examples/neobank/app/wallets/[walletId]/page.tsx, examples/neobank/app/wallets/layout.tsx, examples/neobank/components/StyledTable.tsx
=> feat(neobank): clean up demo IA

examples/levain-graphql-examples/package-lock.json, examples/levain-graphql-examples/src/api/api-cosigning-erc20.ts, examples/levain-graphql-examples/src/api/api-cosigning.ts, examples/levain-graphql-examples/src/app.ts, examples/levain-graphql-examples/src/utils/mutations.ts
=> feat(examples): erc20 transfer example

examples/levain-graphql-examples/.env.example, examples/levain-graphql-examples/api-cosigner-private-key-tron.json.example, examples/levain-graphql-examples/src/api/api-cosigning-erc20.ts, examples/levain-graphql-examples/src/api/api-cosigning-trc20.ts, examples/levain-graphql-examples/src/api/get-network-assets.ts, examples/levain-graphql-examples/src/app.ts, examples/levain-graphql-examples/src/utils/mutations.ts
Adding TRC-20 withdrawal example
Fixes #
=> feat(examples): trc20 withdrawal example

.github/PULL_REQUEST_TEMPLATE.md, .github/renovate.json
=> chore(workflows): add known deps group

examples/neobank/app/wallets/[walletId]/deposit-addresses/page.tsx, examples/neobank/app/wallets/[walletId]/page.tsx, examples/neobank/next.config.js
=> chore(neobank): format and minor DX fixes

examples/neobank/components/RequestSdk.ts
=> fix(neobank): Fixed RequestSDK

examples/levain-sdk-examples/src/api/005-create-wallet-multichain-evm.ts
=> chore(docs): Cleanup evm multichain wallet doc

examples/levain-sdk-examples/src/api/006-create-wallet-multichain-evm-safe.ts
Add example for Safe wallet creation via SDK
=> feat(examples): add multichain evm safe example
